language: node_js
node_js: node
deploy:
  provider: heroku
  app:
    master: cryptic-plains-11682
  api_key:
    secure: JyvqJQnCx4opXZSTJZM9UQkSDT9ZXl2rmoFb8CNi3ri7T+vPjxVjxlrEU4BV1rKi7k+btXr/9vITRuWr4X0A1iCPaQYlqj81V5llbLqQgP3pW82cpT/zRBRbzHaJTsF6cqFM8LZNsqqPNF3DwM06HzFEgcvCCEzxhbF/5kvBagu0cKvm88Mm17A7nX1CqetPNoLyCe5FuSoz7fgD2GsUaoZp7xJWHyIcYY8HheE+HCPeiFZ0hOjGXIaZP52Y2JNCkDKpGY9EG7N7aiHuxn1H/3TUsBJDM8e8nAIz/JoXMR5jHuMZIqAm0RLwwtF2sUE9xatLc8WoBB2mYHrgLAip9xIcZwQj153vgPvDQcUXA71wNEWLDY+ujs8AmbHrf9gvOUcC7ys4wV6Gipe//Cm74zv28pipLch+/ZGpb8CmeO9xuYoTwJHO5Q9bmROSGd5Zcr7CQpVtW3AZJ18Qc0PfJdL5isrLN8XlWcSL7ZNy2UeKioayCkKKE8xrPTODM1bx9CbFy0kssUXNn9mmXhBkStkcnUi29als/mTLJm1b4Wyqn5y42RTayZ8R8Si/CQ/1waRM/oJ12jOmPncSGcQ/wStRZf4eiy4NGHRFiXzm/Snu0giaPko1rqM2aQ+kTOyWIJ+w9Ay/fdufRZ8u39ZoEe1F60g4O0yClMq3qUbhIxU=
