language: node_js
node_js: node
deploy:
  provider: heroku
  app:
    master: cryptic-plains-11682
  api_key:
    secure: Bk8SqOcoxATtbIScbhL8dNhMjuCts7mCCRVLsRP4xbiuwdk7mNcsEOJriqkhpB5pYT2brVonWiFYgSpR+Q9J7kAhgjCOTrFqUFd4Vp++etSEwsEFb4VyJMX4svBHC1G4QXDLI3zSy7e7cII1P5eb9VUx/luf6JEpecXLrf1ylEHzIvxUlXU7hJNWJYb7Mvd4Dao1Lp8fibDo8aLcxxDhn7a0W5L37nxgOcejjs1weurEps+O6ZANZzQjSjqMc1dVn4vR1jIwysF2C/RQoaj4/HxZtM6i7kWft5bFN85VkrNWFdxLP3DgCprA09RiQPtDPPTngouP3LEQxerxBL2vd4oVv9nTcxH6hIeheMRnTQKxYOc98UVS1zggy7pLXIJMXxAoHqrpbZzyHFLCMRSsr+isfOmA9mHSK7rVSDjDrsws2u68iVGj2rmT95tTEe5nYeOtaaSYN5eLtWostUrvt26hKWV9I8chQMzA3R6LtMUtQOmzrmbZgs+H0uNhG3YbEF5azFAVwui61w/oJyE3sZPv7upKDqM++Kpyn1JdpeLFjCfPU1M5q3Pdp3bcYMxSxGTyJbSlaxKupAHxgSGN/TgOyJgXIhPubK4WQcCwhX0PV19G+7fy2AR596IKonOA2szzEM468iSbPppKsw9YG3ZWMBIZ7VBJgm6ZRaEe7sc=
