language: node_js
node_js: node
deploy:
  provider: heroku
  app:
    master: cryptic-plains-11682
  api_key:
    secure: RkuuXQW83g3snrdF5Fx0JT0AOYWfCpLiyQP42Eq/YxI9bjEHKcQ8pzKp8t+Kb7s6vAQFHzABBH3fICivBlAg7UZ9T6T7mkaCNnj8T0JvpFx6zcz4OznXisJRPKg1GgA3EaEe2H23KRdW0gBZ7gfosU7DhSOS7lbn0Moa8qMR/GrQHgjOgq3qHFuQpNawxg1QiIoC46R/+PXiI9Pu11MAaBxETRQi/Yn8c1yzBncYtZfaD77mxxGMhhBYz4wrf4x7SytloxXey3VyWTL+xpXI/VQ62JgwRqr+ydS2k7PRADhof2w8pOF+9cxdN77RMdO+VncCniiC0rQaT6omjwyoffo4N1/pquN/7XFcCaj2XZ5MPsAiBDxwXKvkAVK7LKb/JAdqL/IbkY2wn9WwPhl8+GXpGxKgK4OqBfKqO6/vo2HTdRhjh53hfYVjL/mPO5uFwgRzXMMgQKnnYu9XuZtiRRv4osAnVR4U+zlHQKlI0DPKc4yTVKLSjOsTpTVKEwKIElA9L2dFi5pOVCHr6lRHtPyVBzA5Vw3uZU5AaX8IfOIIlyiUsN3ZEvwLh2fwWMAc9iOBNxXEu05CWvLCKYYZJl61+OhCdCh8Bh6aa4fDgo4DIN/srNxQBOWN32MZ+9LXo3UMAEpuBEXfcxQM/UowoTTygJSAnPxRRK8RqRCUXN0=
